### ISSUE TITLE
Push latest versions to maven repo

### ISSUE THREAD

**Issue by chris-rock** [paypal/invoice-sdk-java#6]
Currently the latest versions are not available via [http://search.maven.org](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.paypal.sdk%22%20AND%20a%3A%22invoicesdk%22) Would it be possible that you publish the lib there?

**Comment by pp-randy** [comment]
Closing this issue, the Maven Search provided appears up to date at this time.
